name: Publish

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
    
permissions:
  contents: write
  
jobs:
  build:
    strategy:
      matrix:
        platfom: [win32, x64]
        configuration: [Release, Release(DLL)]
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Clone
        shell: bash
        run: git clone --recurse-submodules https://github.com/DarthTon/Blackbone
        
      - name: Build solution
        shell: cmd
        run: |
          MSBuild.exe ./Blackbone/BlackBone.sln /p:CI=true /p:Platform="${{ matrix.platfom }}" /p:Configuration="${{ matrix.configuration }}"

      - name: Upload latest artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Blackbone-${{ matrix.platfom }}-${{ matrix.configuration }}
          path: ./Blackbone/build/${{ matrix.platfom }}/${{ matrix.configuration }}/*
          if-no-files-found: error
